Repository slntopp/nocloud, pull requests merged in 2022-10, with the labels that each got.

#446 add auto suspend
  examples/nocloud_n_ione/docker-compose.yml
  pkg/billing/proto/billing.pb.go
  pkg/billing/routines.go
  pkg/dns/proto/dns.pb.go
  pkg/health/proto/health.pb.go
  pkg/instances/proto/instances.pb.go
  pkg/registry/accounts.go
  pkg/registry/proto/accounts/accounts.pb.go
  pkg/registry/proto/accounts/accounts.proto
  pkg/registry/proto/registry.pb.go
  pkg/registry/proto/registry.pb.gw.go
  pkg/registry/proto/registry.proto
  pkg/registry/proto/registry_grpc.pb.go
  pkg/services/proto/services.pb.go
  pkg/services_providers/proto/services_providers.pb.go
  pkg/settings/proto/settings.pb.go
Labels: enhancement, new, go, wip

#443 Add access field
  api.swagger.json
  buf.lock
  docker-compose.yml
  pkg/access/access.pb.go
  pkg/access/access.proto
  pkg/billing/billing.go
  pkg/billing/proto/billing.pb.go
  pkg/billing/records.go
  pkg/billing/transactions.go
  pkg/credentials/credentials.go
  pkg/credentials/standard.go
  pkg/credentials/whmcs.go
  pkg/dns/proto/dns.pb.go
  pkg/graph/account_delete_test.go
  pkg/graph/accounts.go
  pkg/graph/graphs.go
  pkg/graph/instances.go
  pkg/graph/namespaces.go
  pkg/graph/permissions.go
  pkg/graph/records.go
  pkg/graph/services.go
  pkg/graph/transactions.go
  pkg/health/proto/health.pb.go
  pkg/instances/proto/instances.pb.go
  pkg/instances/proto/instances.proto
  pkg/instances/server.go
  pkg/nocloud/admin_auth/auth.go
  pkg/nocloud/auth/auth.go
  pkg/registry/accounts.go
  pkg/registry/accounts_helpers.go
  pkg/registry/namespaces.go
  pkg/registry/proto/accounts/accounts.pb.go
  pkg/registry/proto/accounts/accounts.proto
  pkg/registry/proto/namespaces/namespaces.pb.go
  pkg/registry/proto/namespaces/namespaces.proto
  pkg/registry/proto/registry.pb.go
  pkg/services/proto/services.pb.go
  pkg/services/proto/services.proto
  pkg/services/services.go
  pkg/services_providers/proto/services_providers.pb.go
  pkg/services_providers/proto/services_providers.proto
  pkg/services_providers/server.go
  pkg/settings/proto/settings.pb.go
Labels: go

#478 Fix unsafe Atoi
  pkg/graph/currency.go
Labels: bug, go
